version: "3.3"
services:
   frontend:
      build: ./frontend
      ports:
         - 3000:3000
      environment:
         WATCHPACK_POLLING: "true"
      volumes:
         - ./frontend:/app
      depends_on:
         - backend
   backend:
      build: ./backend
      ports:
         - 3001:3001
      environment:
         PORT: ${PORT}
         NODE_ENV: ${NODE_ENV}
         MONGOATLAS_URI: ${MONGOATLAS_URI}
         MONGOATLAS_URI_TEST: ${{ secrets.MONGOATLAS_URI_TEST }}
      volumes:
         - ./backend:/app
