version: "3.3"
services:
   frontend:
      build: ./frontend
      ports:
         - 3000:3000
      environment:
         WATCHPACK_POLLING: "true"
      volumes:
         - ./frontend:/app
      depends_on:
         - backend
   backend:
      build: ./backend
      ports:
         - 3001:3001
      volumes:
         - ./backend:/app
